import Head from 'next/head'
import Searcher from '../components/Searcher'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Searcher/>
    </div>
  )
}
